all:
  hosts:
    node1:
      ansible_host: master02.k6sy.info 
      ip: 37.60.235.206
      access_ip: 37.60.235.206
  children:
    kube_control_plane:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
    calico_rr:
      hosts: {}
